#!/bin/bash
if [[ -f "/dev/disk/by-label/gh_efi" ]]; then
    mount -L gh_efi /boot/efi
    grub-install --target=x86_64-efi --efi-directory=/boot/efi
    grub-mkconfig -o /boot/grub/grub.cfg
else
    echo "Invalid partition layout detected."
    exit 1
fi