#!/bin/bash
if [[ $EUID -ne 0 ]];
then
    exec pkexec --disable-internal-agent "$0" "$@"
fi
ARG=$1
if [[ "${ARG}" == "enable" ]]; then
    mount -o ro,remount /
    btrfs property set -f / ro true
elif [[ "${ARG}" == "disable" ]]; then
    mount -o rw,remount /
    btrfs property set -f / ro false
else
    echo "Unrecognized option."
fi